<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_Jangan berkecil hati jika</name>
   <tag></tag>
   <elementGuidId>7f309b21-c5c5-4ae4-a598-d6e46d1904e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='tinymce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tinymce</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mce-content-body </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>wysiwyg_content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jangan berkecil hati jika warna gigi Anda yang semula putih, kini berubah. Gigi yang menguning atau menggelap, dialami semua orang seiring pertambahan usia.Beberapa jenis makanan dan minuman, termasuk kopi, teh, wine, sports drinking, permen, dan jenis buah beri, dan saus tomat, juga meninggalkan noda di gigi Anda. Salah satu cara umum untuk mengatasinya adalah dengan menjalani perawatan gigi dengan teknik whitening oleh dokter gigi.Pilihan Perawatan untuk Mendapatkan Gigi PutihPilihan lain, meski hasilnya tidak semaksimal di dokter gigi, adalah melakukan pemutihan gigi sendiri di rumah. Anda bisa mendapatkan perangkatnya di apotek atau toko obat. Whitening tersebut mengandung carbamide peroxide, zat peluntur yang mengangkat noda.Ada yang berupa gel, ada juga yang memakai wadah untuk dikenakan di gigi. Untuk mendapatkan hasil maksimal, sebagian produk menyarankan pemakaian setiap hari, masing-masing selama 30-45 menit, selama sepekan.Jenis whitening lainnya berbentuk plester. Ada kandungan gel berbasis peroxide ini sangat tipis pada plester, dan nyaris tak terlihat.Dengan pemakaian beberapa menit setiap hari selama sepekan, gigi Anda jadi lebih putih dalam beberapa hari. Keunggulan utama whitening jenis ini adalah sangat mudah digunakan, meski hasilnya memang tidak menyamai proses dengan whitening kits.Tips Mempertahankan Warna Putih GigiPerlu diingat, apa pun metodenya, hasil pemutihan gigi tidak ada yang permanen. Rata-rata pengguna dan pasien whitening perlu menjalani perawatan kembali setelah setahun.Namun, ada juga yang gigi putihnya mulai luntur hanya sebulan setelah perawatan, terutama jika rutin mengkonsumsi makanan dan minuman yang menodai gigi. Berikut ini beberapa tips supaya gigi putih Anda bertahan lebih lama.Cermat dalam Mengonsumsi Makanan dan Minuman:Hindari makanan dan minuman yang meninggalkan noda di gigi, misalnya, kopi, teh, red wine, dan soda berwarna gelap. Kabar buruknya, hampir semua makanan dan minuman berpotensi menodai gigi. Para pakar kesehatan gigi menyebut, semua makanan dan minuman yang bisa meninggalkan bercak di kaus katun putih, juga bisa menodai gigi.Hanya saja, noda itu terbentuk secara perlahan dan makin terlihat seiring pertambahan usia. Jika tetap ingin minum minuman tersebut, gunakan sedotan supaya minuman itu tidak menyentuh gigi.Berkumur:Setelah mengonsumsi makanan maupun minuman yang berpotensi meninggalkan noda pada gigi, sebaiknya segera berkumur.Rajin Menyikat Gigi:Jalani ketentuan-ketentuan soal kebersihan mulut. Sikat gigi 2 kali sehari, pakai dental floss sekali sehari untuk mengangkat plak, gunakan obat kumur minimal sekali sehari untuk mematikan bakteri penyebab plak.Gunakan pasta gigi dengan pemutih untuk mengangkat noda permukaan dan mencegah penguningan. Namun, praktisi kesehatan gigi menyarankan penggunaan whitening toothpaste maksimal dua kali sepekan. Sisanya, pakailah pasta gigi biasa.Pantang Merokok:Rokok bukan hanya membahayakan kesehatan, tapi juga memiliki salah satu zat penoda terburuk bagi gigi. Tembakau meninggalkan noda kecokelatan yang bisa menembus email gigi.Noda yang disebabkan tembakau, sulit dihilangkan oleh sikat gigi. Semakin lama Anda merokok, noda akan semakin mengakar. Di mulut, rokok juga membuat bau napas dan memicu gingivitis atau kanker gusi.Perawatan Whitening:Ulangi perawatan whitening. Sebersih apa pun Anda, gigi tetap berisiko menguning. Jangka pemutihan ulang berbeda bagi setiap orang. Ada yang butuh pemutihan enam bulan sekali, ada yang setahun sekali. Jika Anda perokok, kebutuhan akan perawatan ulang jadi lebih sering.id(&quot;tinymce&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tinymce&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/cms/Page_SehatQ/iframe_Formats_wysiwyg_content</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//body[@id='tinymce']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//body</value>
   </webElementXpaths>
</WebElementEntity>
