<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canonical</name>
   <tag></tag>
   <elementGuidId>1385427b-c56c-4f18-adbc-20080c5de199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/head/link[@rel='canonical']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/head/link[@rel='canonical']</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>/html/head/link[@rel='canonical']</value>
   </webElementXpaths>
</WebElementEntity>
